Traceback (most recent call last):
  File "/home/rickyd/Téléchargements/pythonProject100/debug_01.py", line 95, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
